language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master
  - develop
  - prod

addons:
  sonarcloud:
    organization: hahleung-github
    token:
      secure: ycNgk3+dZ/XiM7FZZo1/oGYdH1WpvzIspr3ajvUdpR9zyeKJn2HyQN41lFLhPxSTw218Q6RjGGQxv09Kgd8sZ66j5faEQLYuKH5wWF2a5pCygs300JEBGD+T6Yot8iSWWYpE8ykm8xUR7gNgyhfMBxCpcI/HPnLUxFt3di8TW590bPOTtqjcVc1ESiinjBHhNDc1cO4iX8rsu20S/phQ8jO2umrTh0ltf/aINOux4hY0g5pJjVzOGph3MNIH86sd8h+jLqKOAK7V1XkeUYWbWgpxiv+Ln7QQO07OoLvKcI1LBtLnGmNRms5FdJgbkUvAxOSL3y3pKNQEt7aQqErns/q3R+1wRnUkqrEcpFF89wDg75rizu0wia+AdiMxIA2BYJVqy7I6EhkWfrcewx299VEP7lEcMUBu6+mcn1Dn/Yng7mJcNQwvVdHmpNPb/0GrHJ0gw4ZcYB0MeXEmvZjNxAMAIYl9NyMQXOnEG5khAgj6QnpWUe4GUjicaOKKq0LpL2+eHr5gSYq+/VflHdnyld/sQ+N9WGDlFq7PEjRjClJhohgsISUZ3/FTNE2xadSr+3UdmuporL1RyrOIfGzMvSt+QuTaUZUMBvXCvZ8Kl3wHc3+eQRw4tAVH4sLEAp9lJCZwN4rMtSpvD642fu5zYypvXkKJl1pEP9scdqqRdSI=
    branches:
    - master
    - develop
    - prod

jobs:
  include:
  - stage: Run unit tests
    script: "./gradlew test"
  - stage: Run code quality tool
    script: skip
  - stage: Deploy to staging
    deploy:
      provider: heroku
      app:
        master: ohnana-staging
      api_key:
        secure: YoU/LXh2QN5w0k8q86znXvZXITDz29FtQV/3XStgTrkdoee9bhy+GdhTShwGSh39zh60TeO+PclPXCwQDRyERDCrP7nje/m0NUAZEjvJKZK66b3+e6bnVI5/fuBHLCGoq8dhBvP2rYYhxvj3FDRc8mRkm9KFEg1vp3kjh6hJSBfsBfi22WCAJuMlPYhPm1kuK1Rm7Yf7+yFlXdDgNdykaM20cQ8TPp5hHLxX2UIdcUPmtNsHBiBvQL9tAFqIxz0aQDMAGi46/3EI7l5mH1B1fOIWIZm0nRgrmKFLImpEss8lJsD0Bj7bd1vKE3mXjMGBWv60OHOe7e4trsBzrl784kTSTDfoSJJNTXeVK70R4L10ZEi2IAEDse0Neb9jhtNGeKb8UkPcfS33BkhFTBVli6+rI7rhVvjbUtuXq8W4uLY7lusVP1qJRL8eBWkTH4pNcJFUnK1x1sG8lzKJDBwtyKyhZzjBnjJ+23X2ZgGxhe+BjQt/FavbVbcc2MfK522BcjhCwtkAWJL5EX1RC9fGSf/SqjIELNDuZaULuQOaT1MIyo/niHaR5unrdhzwQDU32BSNLleV/w6ajTOkLbKA4HlxL4ZJQ9nyeAyRhG2AQGrvf/207jPuXobOEGXXW7wUtUBfriYtAKPG7Cu+X0PmR7oUOmy4yeq05Hs1OG3RL64=
      on:
        repo: hervit0/ohnana-whats

env:
  global:
  - secure: XYemp8ST4BKxY6GLUEjclZFiYFN8LdfgqEwBeCcuFXGpiCL8PPIhGq1FGgPPLc94Y5ks0DUFUKVtaubAU1cvINEmvulwGNhgrnVlXpaRKIcdN4aHPy1s5+LbRunw8YtCZFZ3ad4IxOvUxAIlSUW8l+hRcNu95GqHtT2uOrOTthb3I2LLjsoUycq6MaOxd7SS5r3KQyqVY0xHpPToWOqOQDzD5sJY7Wi5dFlYD8YJ8YrkNiOSFXktpUnY0R4pE6oBZ4YPZuwPpeXXWW9h6+bcAXkz5wlQFdbaB7SASCwC17iADcht/DDRperKsuAo/PIbQ/VmrDR7xAzDjsQfz1EGio0kAnGPVN2I19nyhi8tMvVibO3Ga7ZyLcNez2uUgrUAV6MPl3SGxNOI18XKgJ6OVhZ9kiP6Lft+qlhoSsNQyDy1Yi3Tu8zLKoyuSiLZ8XwM9vU3IxVi9edU3VTNuBIaEzI8WWD2pK5xQLkimUnOvOsu6GoWfMMeztX4yFYM/mIbOReu+hXABAGPTzxUXFfMFMAUHONmD7duNzKKqm6dIyx0JKbGdbAm1hAM1QzPLd/Xl8qQZEWWRwMD0SKvLPo1lxtOD0UKZ+1Na7sGs4jOCtFhRwYQTWPEtPZx8zCpH4JV9/2HVkDum+eBJmFDKjw68AX1uXcmZc+NezDw1llj4G4=
  - secure: keg1Xy2qW2M/qfluNQ1iebS8AWOhTwlcusgI4aoLnthZoceCM6JbyvClw2/Tv4hHtWjBsaOKv4Ab9Bk6EUBqoPLnSD2iQPKBhF+cFp3HIRnocvPY2R6nEErBXayQH/gDLp0H16MFQLP3cK9oCFI3IzB4qvb8k8Wq5ebyGV+YgAMuGbCAgYZ2pSGXHpgvLyEuE16Jwe4+hJ6nrAL+MRXxbiPdF7k5PosMi8sgOKE8ZVjpVB6tHJpsQtmobyoiiFHrXKL6RjZCa4ossYrpAwOb+ezAQvOH4ociP4Mw7CkhXjdkRdXVVXhA76wJNyRU/cP+xJd4W4Vvkw97kp3FosYQTaoKNa4W0KFn/lBq5rfo5oQ1kKpFOPylRjTM9cDZgOgTK5v45enjSl5jt/EGKTVcow6R/DlMNN5i2BElUb91QlIf/yzSmONkEf9Ki5uTDqaPq868f8ff9RSLPVFqvEKSMDsDwcmPwhbpE5yPJqDffolxOsCp5rV4L8yuoxexZpRc+U9Z9FswCDwgl3NVgcQKpJYsUx0ypBWvRZgQb+nTGJl2RWTbY/W4Fpkg28NxWl4q5Mh/i0aNmFCtJZffaX4KsXxBCQF5aK0J0r1+sj1LA72IKmbheA3SRwB8cynvEotUoaOgxiNYNKcymQLM2hJ7osgNk//kFyo7HEnZKiEvQOo=
  - secure: zQUG92UsKdOQdbRnl99zvnHee6Dv7SXxVkxxxXvCDm2fYaTlKBHZA0bv3/CXn195BKHBlCW6AVCE38+tYvCOvz0ldbmWUR/ayqBFuUBti2ioVE2ttr2csqWUMihXB3GtJSxPG7Bwi8w365LzmW96QivpYTBclB8DnrKevb6ZYYY3t93PVSueuOr81PQ3Lo3J7t0/hLRZ6YG0FD1jABX/6+v2qNEu9+VcerGb92+smOHuAF2IjOvkugX1AuWqeBt8puIFi6pBwDyf2GDMZTr5FUo28Q92b1RirWM5iBuaddNA0xMZ/0AyJxrpYZQRWp+q20DAHgp22RH6xqn7GkjwEt9UrLG722iflQ5TQdDbvXUciBhJ8mnlcf8ihjWvCPi9U5UoF7ztJvlj3ctyurXGTICfU7LogIhsCNfb0y0XTP/wW8/gGItzv/BXdDfEZ9AI/9QKkEW63pnUnvkROrHW0o7QhbxGlwlOgffzbJIO0SB0vXMggBcBzrbQHomo24XkPu7jsOYxSRXc5umJXOosPbXbY6gp2jfqT/+0A3fQVCitdibEw8sQW6HsJtNzQsSqPyWGoIGVfsnNEHge2mQpTN7LTEg/2//inFt+179pCryBESKOZ25s5BWyaIga42kSzufvmRJ1+JgqDsWDHC+gm3GAaaBc0a2jcEAK3DXx1Tw=
