version: '3'
services:
  ohnana-db:
    image: 'postgres:9.6-alpine'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=springboot
      - POSTGRES_DB=db_ohnana
  ohnana:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - ohnana-db
    ports:
      - '8080:8080'
